// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXgcKqC987ICQqOLr543N_lKHuw8MRWxU',
    appId: '1:57773453551:web:5119f46a3c0561187cab1a',
    messagingSenderId: '57773453551',
    projectId: 'swiftgo-b74fb',
    authDomain: 'swiftgo-b74fb.firebaseapp.com',
    storageBucket: 'swiftgo-b74fb.firebasestorage.app',
    measurementId: 'G-CH9BWNCBET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQLc5glIq8sbpLqOAdHiNMIDoX6ufvX1A',
    appId: '1:57773453551:android:3ee1f10ceeb311c37cab1a',
    messagingSenderId: '57773453551',
    projectId: 'swiftgo-b74fb',
    storageBucket: 'swiftgo-b74fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0cE8lHTkfkjUaulOnqgJZopc6NmOp_HU',
    appId: '1:57773453551:ios:428f417906cd99dc7cab1a',
    messagingSenderId: '57773453551',
    projectId: 'swiftgo-b74fb',
    storageBucket: 'swiftgo-b74fb.firebasestorage.app',
    iosBundleId: 'com.example.optionb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0cE8lHTkfkjUaulOnqgJZopc6NmOp_HU',
    appId: '1:57773453551:ios:428f417906cd99dc7cab1a',
    messagingSenderId: '57773453551',
    projectId: 'swiftgo-b74fb',
    storageBucket: 'swiftgo-b74fb.firebasestorage.app',
    iosBundleId: 'com.example.optionb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXgcKqC987ICQqOLr543N_lKHuw8MRWxU',
    appId: '1:57773453551:web:d63f4eebe6ebb97e7cab1a',
    messagingSenderId: '57773453551',
    projectId: 'swiftgo-b74fb',
    authDomain: 'swiftgo-b74fb.firebaseapp.com',
    storageBucket: 'swiftgo-b74fb.firebasestorage.app',
    measurementId: 'G-W1D41EJGSZ',
  );
}
